### ISSUE TITLE
Allow Halogen rendering with form state

### ISSUE THREAD

**Issue by puffnfresh** [slamdata/purescript-markdown#16]
At the moment each render will generate HTML from Markdown, oblivious to the user's form element input. The form elements will be reset to the default values on each render.

We need to be able to give the current state (maybe even just an array of SlamDownEvents emitted) so that the render will maintain user input and not be reset.

**Comment by jdegoes** [comment]
@puffnfresh Assigning this one to you unless @paf31 can finish it today (don't know his schedule).

**Comment by jdegoes** [comment]
@paf31 Any chance you can take care of this one tonight or tomorrow morning? MongoWorld on Monday. :sob:

**Comment by puffnfresh** [comment]
Was done 14 days ago!

**Comment by jdegoes** [comment]
Damn, too tired. :zzz:
