### ISSUE TITLE
use actual date / date time / time input elements for those types of inputs

### ISSUE THREAD

**Issue by jdegoes** [slamdata/purescript-markdown#24]

**Comment by garyb** [comment]
Are you meaning using the HTML5 input `type="time"` kind of thing for these? Perhaps worth noting they will act as normal text inputs in every browser but Chrome I think.

**Comment by jdegoes** [comment]
> Are you meaning using the HTML5 input type="time" kind of thing for these? Perhaps worth noting they will act as normal text inputs in every browser but Chrome I think.

Yes, but we can polyfill if we like for other browsers — or do you see some issues with that approach?

**Comment by garyb** [comment]
Nope, sounds good to me. :+1:

**Comment by puffnfresh** [comment]
I've got this but it restricts default values for browsers which understand the type.

In those browsers, this README example won't work:

```markdown
start = __ - __ - ____ __ : __ (06-06-2015 8:00 PM)
```

It has to look like this:

```markdown
start = __ - __ - ____ __ : __ (2015-06-06T20:00)
```

That's just how HTML5 specifies `value` attributes on datetime elements being formatted. Is there a requirement to work with the first default value? We can start parsing each type, but it's a bit of work - or we can just defer this feature for now.

**Comment by jdegoes** [comment]
That's fine, we just need to document it, and at some point, convey "warnings" to the user during parsing.

Markdown parse should never fail, but we need a way (e.g. `WriterT`) to output warnings for things that don't seem quite right, and then of course ripple that up to the UI.

**Comment by jdegoes** [comment]
Oh, and we should update the readme so the defaults are correct for the HTML standard.

**Comment by puffnfresh** [comment]
Easy :+1:
