### ISSUE TITLE
Images shouldn't have formatted alt text

### ISSUE THREAD

**Issue by jonsterling** [slamdata/purescript-markdown#46]
We have

```purescript
data Inline 
  = ...
  | Image (List Inline) String -- ![inlines](url)
 ...
```

In `purescript-markdown-halogen`, we had previously been rendering the list of inlines as children of the `img` tag, but this is legal (and I haven't checked to see what happens if you do it). The standard Markdown approach here is for the thing in the square brackets to become the image's "alt text" in the HTML rendering, and this probably needs to be a string rather than formatted text (i.e. a list of inlines).

@jdegoes How do you feel about me changing the constructor to the following?

```purescript
data Inline 
  = ...
  | Image String String -- ![alt-text](url)
 ...

**Comment by paf31** [comment]
I based this on the Common Markdown spec originally, which says

> An image description has inline elements as its contents. When an image is rendered to HTML, this is standardly used as the image’s alt attribute.

So, the recommendation is to use `alt`, which is technically invalid for anything but plain text. Perhaps stripping out the formatting is the right thing to do?

In other renderers, it would be good to keep the inline support IMO. For example it might be nice to be able to render a Markdown document on the console using ANSI codes for things like italics and bold text, ignoring the image and just rendering its placeholder text.

**Comment by jonsterling** [comment]
@paf31 Ah, I see... I was unfamiliar with the Common Markdown specification.

I suppose we could strip out the formatting in our use-case... Thanks!
