### ISSUE TITLE
Add to package-sets

### ISSUE THREAD

**Issue by aztecrex** [slamdata/purescript-markdown#81]
Would be great to see this available via psc-package.  https://github.com/purescript/package-sets

**Comment by aztecrex** [comment]
Adding it was pretty straightforward. Only **purescript-precise** was missing.  

https://github.com/purescript/package-sets/compare/master...aztecrex:master

**Comment by sassela** [comment]
I could also do with this, so I've created a PR https://github.com/purescript/package-sets/pull/152

**Comment by safareli** [comment]
Thanks!
